### ISSUE TITLE
Cannot Create Share

### ISSUE THREAD

**Issue by dnburgess** [ybizeul/hupload#11]
Unable to create shares.

![image](https://github.com/user-attachments/assets/b0857a87-1b6e-4461-b290-1ed50994ff76)

I've tried mapping a custom volume like: 
 - /home/docker/hupload/data:/data

I've tried docker volumes like (with the volume declared as well):
 - huploaddata:/data

I've tried using your docker run script as it is. I've tried converting it to a docker-compose. 

I've tried creating in command-line and in GUIs like Portainer.

Everything results in the same inability to create shares.

 - Docker version 27.1.1, build 6312585
- Docker version 27.1.1, build 6312585

Also, I'm unable to docker exec into the container to modify the config or users

![image](https://github.com/user-attachments/assets/5aa2d6cd-e739-4fcf-ac3e-6ba9c7ca1275)

**Comment by ybizeul** [comment]
This error is returned when directory creation fails. I've added some logs, can you try the `:main` image instead of `:latest` ?

Regarding the container shell I usually consider a good practice to put as little as possible in the container image, but I recognize it's not great for troubleshooting that kind of things.

But for your specific case, if that's about editing configurations, as those should be stored in volumes, you should have some other way to edit (from host OS typically).

If you don't like the idea of mapping files, and rather map a directory, you can do so, and use `CONFIG` environment variable to point to `config.yml`.

For example, create a `data/` and `config/` directories on the host, and mount them on `/data` and `/config` respectively, then set `CONFIG=/config/config.yml`

Does that make sense ?

**Comment by dnburgess** [comment]
I tried manually creating the /config and /data folders:

![image](https://github.com/user-attachments/assets/56918fbc-a600-4bc1-a78d-886e3787f88c)

I'm still unable to create shares.

The logs only give this error when I try to create a share:

`time=2024-08-04T23:22:05.292Z level=ERROR source=routes.go:24 msg=putShare error="cannot create share"`

**Comment by amenolo** [comment]
Enabling data dir write permissions to others solves the issue, in fact seems that the image is configured to default to executing as a `nonroot` user, am I wrong @ybizeul ?

```
root@test:/opt# ll data/
total 12K
drwxr-xrw- 3 root  root  4.0K Aug  5 07:03 ./
drwxr-xr-x 8 root  root  4.0K Aug  5 07:01 ../
drwxr-xr-x 2 65532 65532 4.0K Aug  5 07:11 yogu-fogi-hipu/
```

**Comment by ybizeul** [comment]
Ugh. I do remember something along those lines with the ko packager I use. That doesn’t explain why it’s working with my environment though, probably docker on the Mac is doing some abstraction sharing home directory. 

It does work in a kubernetes environment though, mounting data for over nfs.

**Comment by ybizeul** [comment]
I did some research and it looks like standard practice to run containers as non root users.
In this case, you would have to give the folder to user 65532 after creating the volume, would that make sense ?

I couldn't try it myself as docker for mac seems to be more permissive for some reason.

**Comment by amenolo** [comment]
> it looks like standard practice to run containers as non root users

In my experience not always, anyway not a docker-savvy here so I guess depends on purposes.

Your image is de facto configured to running as the specific `nonroot` user (≠ any other `non root` user) and morover I noticed is lacking shell access so it could be a so called distroless image: no problem with it, but maybe it worth to be specified in the readme 👍

**Comment by ybizeul** [comment]
You're totally right, and maybe I'll offer a `root` image alternative too

**Comment by dnburgess** [comment]
Was able to verify that the chown command works. 

In the readme, the chown command should be this:
```chown 65532:65532 data```

I hope that this can be built into the container deployment in future releases.

I've run into a few other issues now that I'm able to create shares, but I'll open open those separately.

**Comment by ybizeul** [comment]
Thanks !
